test: dev124414
spring:
  thymeleaf:
    cache: true
  datasource:    
    url: jdbc:mysql://db.hzero.org:3306/mysql?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url1: jdbc:mysql://db.hzero.org:3306/mysql1?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url2: jdbc:mysql://db.hzero.org:3306/mysql2?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:com/example/**/sqlMap/*MySql.xml
